version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_ROOT_PASSWORD: '@vkvkdl23'  # root 사용자의 비밀번호 설정
    ports:
      - '3307:3306'  # 호스트 포트를 3307로 변경

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
